#!/bin/sh

# do not actually do this. The key check is a security feature...

login_user=pi

if [ -n $1 ]; then
	ssh -o StrictHostKeyChecking=no $login_user@$1
fi

# run as "ssh_script $1" where $1 is the hostname
# example: ssh_script 192.168.0.24
# will prompt for password to ssh to pi@192.168.0.24
